name: Lint and Format

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff isort

    - name: Run Ruff
      run: ruff check . --fix

    - name: Run isort
      run: isort .